routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/redi/{id}', 'RedirectController@index') ->where('id', '[0-9]+')->name('redi');
//Route::get('/redi/{id}', 'RedirectController@index') ->where('id', '[0-9]+')->name('redi');

/*Route::group(['middleware' => 'web', 'namespace' => 'App\Http\Controllers'], function () {
    Route::get('/password-reset', 'Auth\ResetPasswordController@showResetForm')
        ->name('cognito.password-reset');
});*/
Route::get('/test', 'TestController@index')->name('test');
Route::get('api.colaboradores','ColaboradoresController@index')->name('api.colaboradores');
Route::get('api.getcolaboradores','ColaboradoresController@getColaboradores')->name('api.getcolaboradores');
Route::post('/getMetricas', 'ColaboradoresController@getMetricas')->name('getMetricas');
;
Route::post('/colaboraFiltro', 'ColaboradoresController@colaboraFiltro')->name('colaboraFiltro');

Route::resource('empleados','EmpleadosController');
Route::get('/metricas','Informes\MetricasController@index')->name('metricas');
Route::post('/newMetric', 'Informes\MetricasController@nuevaMetrica')->name('nuevaMetrica');
Route::get('/metricasone/{id}', 'Informes\MetricasController@show') ->where('id', '[0-9]+')->name('show');
Route::get('/informes','Informes\MetricasController@informesIndex')->name('informesIndex');
Route::post('/metricasFiltro', 'Informes\MetricasController@metricasFiltro')->name('metricasFiltro');

///Chat
Route::get('/contacts', 'ContactsController@get');
Route::get('/conversation/{id}', 'ContactsController@getMessagesFor');
Route::post('/conversation/send/', 'ContactsController@send');



//CaseManagement
Route::get('api.CCDashBoard','Soporte\TestSoporteController@index')->name('api.CCDashBoard');
Route::get('api.tickets','Soporte\TestSoporteController@tickets')->name('api.tickets');
Route::get('api.gettickets','Soporte\TestSoporteController@getTickets')->name('api.gettickets');
//Route::get('/soporte','Soporte/TestSoporteController@tickets')->name('tickets');

resources/views/rh/acciones.blade.php
<a href="{{ route('empleados.show',$id_colaborador) }}">Ver</a>

resources/views/rh/appiandash.blade.php
@extends('layouts.admin')
@extends('rh.menu')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h5 class="m-0 text-dark">Colaboradores</h5>
          </div>

          <div class="col-sm-6">
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

            


    <!-- Main content -->
   <!-- <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-tittle">ddd</h3>
            </div>
            <div class="box-body">
              <div class="col-xs-6"></div>
            </div>
          </div>
        </div>
      </div>
    </section>-->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <div class="car-title">
                  <!--<div class="row">

                      <div class="col-md-2"><button id="dataBtn" class="btn btn-info btn-block btn-sm act" onclick="changeTask('dataBtn');"><i class="fa fa-fw fa-user"></i> Datos</button></div>
                      <div class="col-md-2"><button id="metricsBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('metricsBtn');"><i class="fa fa-fw fa-line-chart"></i> Metricas</button></div>
                      <div class="col-md-2"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Expediente</button></div>
                 
                        
                  </div> -->
                  <div class="row">
                    <div class="col-lg-6">
                    <div class="row" id="arre">
                      
                        <div class="col-md-3"><button id="dataBtn" class="btn btn-primary btn-block" onclick="changeTask('dataBtn','cPMY3Q');"><i class="fa fa-fw fa-user"></i> Datos</button></div>
                        <div class="col-md-3"><button id="metricsBtn" class="btn btn-outline-primary btn-block" onclick="loadView('metricsBtn');"><i class="fa fa-fw fa-line-chart"></i> Metricas</button></div>
                        <!--<div class="col-md-3"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Expediente</button></div>
                        <div class="col-md-3"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Reconocimientos</button></div> -->

                    </div>
                    </div>
                    <div class="col-lg-6">
                     <!-- <div class="row">
                        
                          <div class="col-md-3"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Compensaciones</button></div>
                          <div class="col-md-3"><button id="metricsBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('metricsBtn');"><i class="fa fa-fw fa-line-chart"></i> Metricas</button></div>
                          <div class="col-md-3"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Expediente</button></div>
                          <div class="col-md-3"><button id="fileBtn" class="btn btn-info btn-block btn-outline-info btn-sm act" onclick="changeTask('fileBtn');"><i class="fa fa-fw fa-folder"></i>Expediente</button></div>
                      </div> -->
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <input type="hidden" id="idColaborador" value="<?php echo $id_colaborador; ?>">
                  <div class="col-md-12" id="appianContentDiv">
                      <?php 
                        //echo $id_colaborador;
                      ?> 
                      <appian-record-view recordTypeUrlStub="cPMY3Q" recordIdentifier="<?php echo $id_colaborador; ?>" recordViewUrlStub="summary"></appian-record-view>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

@section('scriptpage')
<!-- DataTable -->
  <!-- This script loads the Appian Web components; change it to your Appian server's domain -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
       <script src="https://mbgedev.appiancloud.com/suite/tempo/ui/sail-client/embeddedBootstrap.nocache.js" id="appianEmbedded"></script>
       <script>
            $.ajaxSetup({
            headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
          });
            window.addEventListener("click", () => {
              console.log("click!!!");
            });
         function changeTask(task,idappian){
            var idcolabora = $('#idColaborador').val();
            $("#divid").load(" #divid"); //Te refresca únicamente el DOM con el ID que le digas. Obligatorio el espacio después del load tal y como aparece
            
            ///$('.act').addClass('btn-outline-primary');
           // $('#'+task).removeClass('btn-outline-primary');
               $('#metricsBtn').removeClass('btn-primary')
          $('#metricsBtn').addClass('btn-outline-primary')
          $('#dataBtn').removeClass('btn-outline-primary');
          $('#dataBtn').addClass('btn-primary')

            $("#appianContentDiv").empty();
            
            $("#appianContentDiv").append('<appian-record-view recordTypeUrlStub="'+idappian+'" recordIdentifier="'+$('#idColaborador').val()+'" recordViewUrlStub="summary"></appian-record-view>')
            /*$('appian-record-view').attr({
              recordIdentifier: idcolabora,
              recordViewUrlStub: task
            }); */
           
            //$("#appianContentDiv").load(" #appianContentDiv");
         }
         function loadView(task){
           
           // $('#dataBtn').removeAttr('class')
           // $('#metricsBtn').removeAttr('class');
           // $('#dataBtn').attr('class', 'btn btn-primary-outline btn-block')
           // $('#metricsBtn').attr('class', 'btn btn-primary btn-block')




          $('#dataBtn').removeClass('btn-primary')
          $('#dataBtn').addClass('btn-outline-primary')
          $('#metricsBtn').removeClass('btn-outline-primary');
          $('#metricsBtn').addClass('btn-primary')
          

         // $('.act').addClass('btn-outline-primary');
            //$('#'+task).removeClass('btn-outline-primary');
          var idcolabora = $('#idColaborador').val();
          //alert('eees')
            $.ajax({
              url: "/getMetricas",
              type: 'POST',
              dataType: 'json',
              data: {idcolabora: idcolabora},
            })
            .done(function(data) {
              //console.log(data);
              //alert('dddd');
              $("#appianContentDiv").empty();
            
              $("#appianContentDiv").append(data.html)
               //$('#tableMetrics').DataTable();
      $("#metricsDiv").load("#appianContentDiv");

          $("#metricsDiv").load("#appianContentDiv");
            })
            .fail(function() {
              console.log("error");
            })
            .always(function() {
              console.log("complete");
            });
          
         }
         function seeMetric(id){
           
            $("#appianContentDiv").empty();
            
            $("#appianContentDiv").append('<appian-record-view recordTypeUrlStub="1qrd0A" recordIdentifier="'+id+'" recordViewUrlStub="summary"></appian-record-view>')
         }
         function newMetric(){
          var idcolabora = $('#idColaborador').val();
          //alert(idcolabora);
             $.ajax({
               url: '/newMetric',
               type: 'POST',
               dataType: 'json',
              data: {idcolabora: idcolabora},
             })
             .done(function(data) {
               console.log(data);
               //alert(data.html);
                $("#appianContentDiv").empty();
            
              $("#appianContentDiv").append('<appian-task taskId="'+data.html+'"></appian-task>')
             })
             .fail(function() {
               console.log("error");
             })
             .always(function() {
               console.log("complete");
             });
             
           }
       </script>

@endsection

resources/views/rh/human_rocketin.blade.php
@extends('layouts.admin')
@extends('rh.menu')
@section('content')
    <!-- Content Header (Page header) -->

            


    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
<div class="row"></div>
        <br><br>
        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-2">
            
          </div>
          <div class="col-md-2">
           <!-- <div class="hexagono2" style="float:left;" id="atraccionHex">
              <span class="hexagono-content">
                <i class="fa fa-search fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion y Seleccion de talento</strong>
              </span>
            </div>-->
          </div>
          <div class="col-md-2">
            <a href="{{ action('ColaboradoresController@index', ['id' => 1]) }}">
            <div class="hexagono2" style="float:left; background-color: #F64BEE" id="colaboradorHex">
              <span class="hexagono-content">
                <i class="fa fa-users fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Colaboradores</strong>
              </span>
            </div>
            </a>
          </div>
          <div class="col-md-2">
           <!-- <div class="hexagono2" style="float:left;" id="retencionHex">
              <span class="hexagono-content">
                <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Retencion de Talento</strong>
              </span>
            </div>-->
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-1">
          </div>
          <!--<div class="col-sm-12">
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
          </div> -->
        </div>
        <br><br>
        <div class="row">
        <!--  <div class="col-md-6">
            <div class="row">
              <div class="col-sm-4"></div>
              <div class="col-sm-4">
              <div class="hexagono2" style="float:left;" id="compensacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion Talento</strong>
              </span>
            </div>
              </div>
              <div class="col-sm-4">
                            <div class="hexagono2" style="float:left;" id="compensacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion Talento</strong>
              </span>
            </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="row">
              
              <div class="col-sm-2">
                            <div class="hexagono2" style="float:left;" id="compensacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion Talento</strong>
              </span>
            </div>
              </div>
              <div class="col-sm-2">
                            <div class="hexagono2" style="float:left;" id="compensacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion Talento</strong>
              </span>
            </div>
              </div>
              <div class="col-sm-8"></div>
            </div>
          </div> -->



           
          <div class="col-md-2"></div>
          <div class="col-md-2">
            <div class="hexagono2" style="float:left;margin-left: 30%;" id="compensacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-user-plus fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Atraccion Talento</strong>
              </span>
            </div>
          </div>
          <div class="col-md-2">
            <div class="hexagono2" style="float:left;" id="desarrolloHex">
              <span class="hexagono-content">
                <i class="fa fa-line-chart fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Desarrollo Organizacional</strong>
              </span>
            </div>
          </div>
          <div class="col-md-1">
            <div class="hexagono2" style="float:left;" id="saludHex">
              <span class="hexagono-content">
                <i class="fa fa-heartbeat fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Salud y Seguridad</strong>
              </span>
            </div>
          </div>
          <div class="col-md-2">
      
            <div class="hexagono2" style="float:left;margin-left:25%;" id="relacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Retencion Talento</strong>
              </span>
            </div>
          
          </div>

          <div class="col-md-2"></div>
          <!--<div class="col-sm-12">
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
            <div class="hexagono2" style="float:left;"></div>
          </div> -->
        </div>
        <br><br>
        <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-2">
            <div class="hexagono2" style="float:left;" id="relacionesHex">
              <span class="hexagono-content">
                <i class="fa fa-handshake-o fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Relaciones Laborales</strong>
              </span>
            </div>
          </div>
          <div class="col-md-5"></div>
        </div>
        <br><br>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md 2">
            <div class="hexagono2" style="float:left;" id="saludHex">
              <span class="hexagono-content">
                <i class="fa fa-balance-scale fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Compensaciones Beneficios</strong>
              </span>
            </div>
          </div>
          <div class="col-md 2">
            <a href="{{ action('Informes\MetricasController@informesIndex') }}">
            <div class="hexagono2" style="float:left;background-color: #23A471" id="saludHex">
              <span class="hexagono-content">
                <i class="fa fa-bar-chart fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Informes</strong>
              </span>
            </div>
            </a>
          </div>
          <div class="col-md-4"></div>
        </div>
        <br>
        <br>
      
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-2">
            <div class="hexagono2" style="float:left;" id="saludHex">
              <span class="hexagono-content">
                <i class="fa fa-book fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Documentacion</strong>
              </span>
            </div>
          </div>
          <div class="col-md-2"></div>
          <div class="col-md-2">
            <div class="hexagono2" style="float:left;background-color: #4184FA" id="saludHex">
              <span class="hexagono-content">
                <i class="fa fa-gears fa-2x" aria-hidden="true"></i>
                <br>
                <strong style="font-size: 70%;">Sistema</strong>
              </span>
            </div>
          </div>
          <div class="col-md-3"></div>
        </div>
     <!-- <div class="row">
          <div class="col-lg-3 col-6">
            <div class="small-box bg-info">
              <div class="inner">
                <h3>150</h3>
                <p>New Orders</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <div class="col-lg-3 col-6">
            <div class="small-box bg-success">
              <div class="inner">
                <h3>53<sup style="font-size: 20px">%</sup></h3>
                <p>Bounce Rate</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <div class="col-lg-3 col-6">
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>44</h3>
                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <div class="col-lg-3 col-6">
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>65</h3>
                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
          </div>
        </div> -->
        <!-- /.row (main row) -->

      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/rh/listam.blade.php
                <div class="row">
                  <div class="col-md-12">
                   <!-- <table class="table-bordered table-hover" id="tableMetrics" style="width: 100%;">
                      <thead>
                        <tr>
                          <th>Estatus</th>
                          <th>Nombre</th>
                          <th>Inicio</th>
                          <th>Final</th>
                          <th>Resultado</th>
                          <th>Observacsssiones</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($metricas as $un)
                          <tr>
                            <td>{!! $un['cerrada'] !!}</td>
                            <td>{!! $un['nombre'] !!}</td>
                            <td>{{ $un['fecha_ini'] }}</td>
                            <td>{{ $un['fecha_fin'] }}</td>
                            <td>{!! $un['resultado'] !!}</td>
							              <td>{{ $un['observaciones'] }}</td>
                          </tr>   
                      @endforeach
                      </tbody>
                    </table>-->
                    <table class="table table-bordered table-hover table-striped w-100" id="tableMetrics">
                      <thead class="bg-warning-200">
                        <tr>
                          <th>Estatus</th>
                          <th>Nombre</th>
                          <th>Inicio</th>
                          <th>Final</th>
                          <th>Resultado</th>
                          <th>Observacsssiones</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($metricas as $un)
                          <tr>
                            <td>{!! $un['cerrada'] !!}</td>
                            <td>{!! $un['nombre'] !!}</td>
                            <td>{{ $un['fecha_ini'] }}</td>
                            <td>{{ $un['fecha_fin'] }}</td>
                            <td>{!! $un['resultado'] !!}</td>
                            <td>{{ $un['observaciones'] }}</td>
                          </tr>   
                      @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
<script>
  $(document).ready(function() {
 
  $('#tableMetrics').DataTable({
      language: {
          "decimal": "",
          "emptyTable": "No hay información",
          "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
          "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
          "infoFiltered": "(Filtrado de _MAX_ total entradas)",
          "infoPostFix": "",
          "thousands": ",",
          "lengthMenu": "Mostrar _MENU_ Entradas",
          "loadingRecords": "Cargando...",
          "processing": "Procesando...",
          
          "zeroRecords": "Sin resultados encontrados",
          "paginate": {
              "first": "Primero",
              "last": "Ultimo",
              "next": "Siguiente",
              "previous": "Anterior"
          }
      },
      responsive : true,
      dom: "<'row mb-3'<'col-sm-12 col-md-6 d-flex align-items-center justify-content-start'f><'col-sm-12 col-md-6 d-flex align-items-center justify-content-end'B>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>", 
      buttons: [
          {
              extend: 'colvis',
              text: '<i class="fas fa-columns"></i>&nbsp;Columnas',
              titleAttr: 'Mostrar/Ocultar Columnas',
              className: 'btn-outline-primary btn-sm mr-1'
          },
          {
              extend: 'pdfHtml5',
              text: '<i class="fas fa-file-pdf"></i>&nbsp; PDF',
              titleAttr: 'Generar PDF',
              className: 'btn-outline-danger btn-sm mr-1'
          },
          {
              extend: 'excelHtml5',
              text: '<i class="fas fa-file-excel"></i>&nbsp; Excel',
              titleAttr: 'Generar Excel',
              className: 'btn-outline-success btn-sm mr-1'
          },
          {
              extend: 'copyHtml5',
              text: '<i class="fas fa-copy"></i> &nbsp;Copiar',
              titleAttr: 'Copiar Tabla',
              className: 'btn-outline-primary btn-sm mr-1'
          },
          {
              extend: 'print',
              text: '<i class="fas fa-print"></i>&nbsp; Imprimir',
              titleAttr: 'Imprimir Tabla',
              className: 'btn-outline-primary btn-sm'
          },
          {
              text: '<a href="javascript:void(0);" class="btn btn-outline-primary btn-lg btn-icon rounded-circle hover-effect-dot waves-effect waves-themed" onclick="newMetric()"><i class="fa fa-plus" aria-hidden="true"></i></a>',
              titleAttr: 'Alta Metrica',
          }

      ],
    }); 
$("#metricsDiv").load("#appianContentDiv");

  });

</script>

resources/views/rh/metricas.blade.php
                <div class="row">
                  <div class="col-md-12" id="metricsDiv">
                   <!-- <table class="table table-bordered table-hover table-striped w-100" id="tableMetrics">
                      <thead class="bg-warning-200">
                        <tr>
                          <th>Estatus</th>
                          <th>Nombre</th>
                          <th>Inicio</th>
                          <th>Final</th>
                          <th>Resultado</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($metricas as $un)
                          <tr>
                            <td>{{ $un['cerrada'] }}</td>
                            <td>{{ $un['nombre'] }}</td>
                            <td>{{ $un['fecha_ini'] }}</td>
                            <td>{{ $un['fecha_fin'] }}</td>
                            <td>{{ $un['resultado'] }}</td>
                          </tr>   
                      @endforeach
                      </tbody>
                    </table> -->
                    <table class="table table-bordered table-hover table-striped w-100" id="tableMetrics">
                      <thead class="bg-warning-200">
                        <tr>
                          <th>Estatus</th>
                          <th>Nombre</th>
                          <th>Inicio</th>
                          <th>Fin</th>
                          <th>Resultado</th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach ($metricas as $un)
                          <tr>
                            <td>{{ $un['cerrada'] }}</td>
                            <td>{{ $un['nombre'] }}</td>
                            <td>{{ $un['fecha_ini'] }}</td>
                            <td>{{ $un['fecha_fin'] }}</td>
                            <td>{{ $un['resultado'] }}</td>
                          </tr>   
                      @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>